name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write   # allow pushing tags, changelog, and commits

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # important for semantic-release to see all commits

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - run: npm ci

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # use the default GitHub Actions token
        run: npx semantic-release
